BUDDHA_NUM = 0
JESUS_NUM = 1
ALLAH_NUM = 2
AUTHOR_NUM = 3

SMART_LEVEL = 10
DUMMY_LEVEL = -SMART_LEVEL

GOD_LEVEL = 3

DICE_MAX = 32
DICE_MIDDLE = DICE_MAX / 2

INVENTORY_PAGE_SIZE = 5

AURA_BUDDHA = 'мир'
WATER = 'вода'
FIRE = 'огонь'
STONE = 'камень'
AIR = 'воздух'
DEAD = 'мертвец'
NONE = 'нет'

EVIL_MUSCLELOT = 'evil_musclelot'
JAPANESE = 'japanese'

SLIME_STICKER = 'BQADAgAD7AADDLXzAxPOv_f69TwOAg'

HUMAN = 'human'
RAT_RACE = 'rat'